### ISSUE TITLE
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(exception, Internal error, invalidArgument("CGPDFDocument is nil"), null)

### ISSUE THREAD

**Issue by lhpfu64** [espresso3389/flutter_pdf_render#103]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(exception, Internal error, invalidArgument("CGPDFDocument is nil"), null)
#0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:653:7)
#1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:296:18)
<asynchronous suspension>
#2      PdfRenderPlatformMethodChannel.openFile (package:pdf_render/src/pdf_render_method_channel.dart:32:18)
<asynchronous suspension>
#3      HomeController.convert (package:pdf2image/app/modules/home/controllers/home_controller.dart:31:17)
<asynchronous suspension>
```

```
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.3.10, on macOS 12.3.1 21E258 darwin-x64, locale zh-Hans-CN)
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 13.4.1)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2021.3)
[✓] Android Studio (version 2021.3)
[✓] IntelliJ IDEA Ultimate Edition (version 2022.2)
[✓] VS Code (version 1.74.2)
[!] Proxy Configuration
    ! NO_PROXY does not contain ::1
[✓] Connected device (2 available)
[✓] HTTP Host Availability

```

```
  pdf_render: ^1.3.6
```

**Comment by espresso3389** [comment]
Your code seems to call the internal API directly. I don't forbid you to do such things but the internal interface may be changed in future without any explicit notice.

OK, I don't know what you're doing and it's impossible to discuss about the error without your actual code. Could you please show me your codes.
