### ISSUE TITLE
Add PdfDocument info as argument in buildPageOverlay

### ISSUE THREAD

**Issue by niktekusho** [espresso3389/flutter_pdf_render#110]
Thank you for this very cool library!

I'm currently trying to render some rectangles on top of specific PDF pages (for example only on pages 1, 3, and 4).
These rectangles should be positioned relative to specific PDF coordinates (for example rectangle on page 1 needs to be located at `(x:100,y:200)`, while the pdf page is `500 points wide` and `800 points high`).
Is `buildPageOverlay` a good fit for what I'm trying to achieve?
If it is, in order to keep the appropriate proportions, I would need to access the size of the currently rendered page.
Do you think it's feasible to pass the whole PdfDocument as an argument?
From the PdfDocument then I could get the currentPage (and its size) thanks to the pageIndex passed in `buildPageOverlay`.

I understand that the whole PdfDocument object might be a bit too much; maybe we could pass at least the list of sizes of the pages?

**Comment by espresso3389** [comment]
[1.3.8](https://pub.dev/packages/pdf_render/versions/1.3.8) introduces [PdfViewerController.getPage](https://pub.dev/documentation/pdf_render/latest/pdf_render_widgets/PdfViewerController/getPage.html) method to get [PdfPage](https://pub.dev/documentation/pdf_render/latest/pdf_render/PdfPage-class.html).

So you can use the controller to get the original page size in points (that is the pixel size at 72 dpi).

**Comment by niktekusho** [comment]
Thank you so much for the quick implementation! I'm going to try this out in the next few days so I'll be closing this issue for now. Thank you again!

**Comment by niktekusho** [comment]
I think I found something not working as expected; it might be caused by my wrong usage of the components, though.
I manage to reproduce my issue in your example project.

Let me know if I should bring this to a new issue or reopen this one :wink: 

This is the `main.dart` to reproduce the issue:

```dart
import 'dart:io';

import 'package:flutter/foundation.dart'
    show kIsWeb; // for checking whether running on Web or not
import 'package:flutter/material.dart';
import 'package:flutter_cache_manager/flutter_cache_manager.dart';
import 'package:pdf_render/pdf_render_widgets.dart';

void main(List<String> args) => runApp(const MyApp());

class MyApp extends StatefulWidget {
  const MyApp({Key? key}) : super(key: key);

  @override
  _MyAppState createState() => _MyAppState();
}

class _MyAppState extends State<MyApp> {
  final controller = PdfViewerController();

  TapDownDetails? _doubleTapDetails;

  final _overlaysStates = {for (final overlay in overlays) overlay.id: false};

  @override
  void dispose() {
    controller.dispose();
    super.dispose();
  }

  Widget _createOverlay(Rect pageRect, Overlay overlay) {
    final pageNumber = controller.ready?.currentPageNumber ?? 1;
    final pdfPage = controller.ready?.getPageRect(pageNumber);

    if (pdfPage == null) {
      return const SizedBox.shrink();
    }

    return Positioned(
      top: pdfPage.longestSide * overlay.topRelativeToPdfHeight,
      left: pdfPage.shortestSide * overlay.leftRelativeToPdfWidth,
      child: GestureDetector(
        onTap: () {
          setState(() {
            _overlaysStates[overlay.id] = !_overlaysStates[overlay.id]!;
          });
        },
        child: Container(
          width: 200,
          height: 30,
          color: _overlaysStates[overlay.id]!
              ? Colors.green
              : Colors.black.withOpacity(0.5),
          child: Center(
            child: Text(
              overlay.text,
              style: const TextStyle(
                color: Colors.white,
              ),
            ),
          ),
        ),
      ),
    );
  }

  Widget _renderOverlay(
    BuildContext context,
    int pageNumber,
    Rect pageRect,
  ) {
    return ValueListenableBuilder<Matrix4>(
      valueListenable: controller,
      builder: (context, _, child) => Stack(
        children: overlays
            .where((overlay) => overlay.page == pageNumber)
            .map((overlay) => _createOverlay(pageRect, overlay))
            .toList(),
      ),
    );
  }

  void _goToNextOverlay() {
    if (controller.isReady) {
      print('Controller ready');
    } else {
      print('Controller not ready');
      return;
    }

    final currentPage = controller.ready?.currentPageNumber ?? 1;

    // print('Current Page $currentPage');

    final greyOverlays = _overlaysStates.entries
        .where((entry) => entry.value == false)
        .map((entry) => entry.key)
        .toSet();

    // print('Grey Overlays $greyOverlays');

    Overlay? nextOverlay;

    for (final overlay in overlays) {
      if (greyOverlays.contains(overlay.id) && overlay.page >= currentPage) {
        nextOverlay = overlay;
        break;
      }
    }

    nextOverlay ??=
        overlays.firstWhere((overlay) => greyOverlays.contains(overlay.id));

    // print('Next overlay: ${nextOverlay.id}');

    final page = controller.ready?.getPage(nextOverlay.page);

    if (page == null) {
      print('Page ${nextOverlay.page} is null. This should not happen...');
      return;
    }

    controller.ready?.goToPointInPage(
      pageNumber: nextOverlay.page,
      x: (nextOverlay.leftRelativeToPdfWidth / page.width) *
          controller.ready!.viewRect.width,
      y: (nextOverlay.topRelativeToPdfHeight / page.height) *
          controller.ready!.viewRect.height,
    );
  }

  void _resetOverlays() {
    setState(() {
      _overlaysStates.updateAll((key, value) => false);
    });
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      home: Scaffold(
        appBar: AppBar(
          title: ValueListenableBuilder<Matrix4>(
              // The controller is compatible with ValueListenable<Matrix4> and you can receive notifications on scrolling and zooming of the view.
              valueListenable: controller,
              builder: (context, _, child) => Text(controller.isReady
                  ? 'Page #${controller.currentPageNumber}'
                  : 'Page -')),
        ),
        backgroundColor: Colors.grey,
        body: GestureDetector(
          // Supporting double-tap gesture on the viewer.
          onDoubleTapDown: (details) => _doubleTapDetails = details,
          onDoubleTap: () => controller.ready?.setZoomRatio(
            zoomRatio: controller.zoomRatio * 1.5,
            center: _doubleTapDetails!.localPosition,
          ),
          child: !kIsWeb && Platform.isMacOS
              // Networking sample using flutter_cache_manager
              ? PdfViewer.openFutureFile(
                  // Accepting function that returns Future<String> of PDF file path
                  () async => (await DefaultCacheManager().getSingleFile(
                          'https://github.com/espresso3389/flutter_pdf_render/raw/master/example/assets/hello.pdf'))
                      .path,
                  viewerController: controller,
                  onError: (err) => print(err),
                  params: PdfViewerParams(
                    padding: 10,
                    minScale: 1.0,
                    // scrollDirection: Axis.horizontal,
                    buildPageOverlay: _renderOverlay,
                  ),
                )
              : PdfViewer.openAsset(
                  'assets/hello.pdf',
                  viewerController: controller,
                  onError: (err) => print(err),
                  params: PdfViewerParams(
                    padding: 10,
                    minScale: 1.0,
                    // scrollDirection: Axis.horizontal,
                    buildPageOverlay: _renderOverlay,
                  ),
                ),
        ),
        floatingActionButton: Column(
          mainAxisAlignment: MainAxisAlignment.end,
          children: <Widget>[
            FloatingActionButton(
              onPressed: _resetOverlays,
              child: const Icon(Icons.delete),
            ),
            if (_overlaysStates.values.any((state) => state != true))
              FloatingActionButton(
                child: const Icon(Icons.next_plan),
                onPressed: _goToNextOverlay,
              )
          ],
        ),
      ),
    );
  }
}

class Overlay {
  final int id;
  final int page;
  final String text;
  final double leftRelativeToPdfWidth;
  final double topRelativeToPdfHeight;

  const Overlay({
    required this.id,
    required this.page,
    required this.text,
    required this.leftRelativeToPdfWidth,
    required this.topRelativeToPdfHeight,
  });
}

const overlays = [
  Overlay(
    id: 1,
    page: 1,
    text: 'Overlay 1',
    leftRelativeToPdfWidth: 0.2,
    topRelativeToPdfHeight: 0.1,
  ),
  Overlay(
    id: 2,
    page: 2,
    text: 'Overlay 2',
    leftRelativeToPdfWidth: 0.5,
    topRelativeToPdfHeight: 0.5,
  ),
];

```

## Steps to reproduce

1. copy the mentioned `main.dart` above into the `example/lib` folder of this repository
   - rename the existing one or use `git` to undo changes later
2. run the app on an Android emulator
3. click on the first overlay and then on the floating action button

## Expected behaviour

The floating action button should bring the user to the next overlay

## Actual behaviour

Flutter errors out with the following relevant log:

```
I/flutter (12323): Controller ready

════════ Exception caught by gesture ═══════════════════════════════════════════
The following LateError was thrown while handling a gesture:
LateInitializationError: Field 'pdfPage' has not been initialized.

When the exception was thrown, this was the stack
#0      _PdfPageState.pdfPage (package:pdf_render/pdf_render_widgets.dart)
pdf_render_widgets.dart:1
#1      PdfViewerController.getPage
pdf_render_widgets.dart:529
#2      _MyAppState._goToNextOverlay
main.dart:116
#3      _InkResponseState.handleTap
ink_well.dart:1096
#4      GestureRecognizer.invokeCallback
recognizer.dart:253
#5      TapGestureRecognizer.handleTapUp
tap.dart:627
#6      BaseTapGestureRecognizer._checkUp
tap.dart:306
#7      BaseTapGestureRecognizer.handlePrimaryPointer
tap.dart:239
#8      PrimaryPointerGestureRecognizer.handleEvent
recognizer.dart:615
#9      PointerRouter._dispatch
pointer_router.dart:98
#10     PointerRouter._dispatchEventToRoutes.<anonymous closure>
pointer_router.dart:143
#11     _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:625:13)
#12     PointerRouter._dispatchEventToRoutes
pointer_router.dart:141
#13     PointerRouter.route
pointer_router.dart:127
#14     GestureBinding.handleEvent
binding.dart:460
#15     GestureBinding.dispatchEvent
binding.dart:440
#16     RendererBinding.dispatchEvent
binding.dart:336
#17     GestureBinding._handlePointerEventImmediately
binding.dart:395
#18     GestureBinding.handlePointerEvent
binding.dart:357
#19     GestureBinding._flushPointerEventQueue
binding.dart:314
#20     GestureBinding._handlePointerDataPacket
binding.dart:295
#21     _invoke1 (dart:ui/hooks.dart:164:13)
#22     PlatformDispatcher._dispatchPointerDataPacket (dart:ui/platform_dispatcher.dart:361:7)
#23     _dispatchPointerDataPacket (dart:ui/hooks.dart:91:31)
Handler: "onTap"
Recognizer: TapGestureRecognizer#bb383
    debugOwner: GestureDetector
    state: possible
    won arena
    finalPosition: Offset(1403.3, 978.6)
    finalLocalPosition: Offset(35.3, 26.6)
    button: 1
    sent tap down
════════════════════════════════════════════════════════════════════════════════
```

**Comment by niktekusho** [comment]
Friendly bump :wink:

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA

**Comment by jjochen** [comment]
@niktekusho maybe moving this to a new issue would make sense

**Comment by niktekusho** [comment]
Sorry @jjochen but I don't have enough time to create a proper issue atm. Please, feel free to take the pieces you need from this issue and create a new one (I'll subscribe to that issue too).
