### ISSUE TITLE
Unhandled Exception: Null check operator used on a null value

### ISSUE THREAD

**Issue by Yousafkhanzadaa** [espresso3389/flutter_pdf_render#138]
Hi, I am trying to show the first page of the pdf file as a Thumbnail, using the code below. But I am getting error:

**Code:**
```
PdfDocumentLoader.openFile(
  pdf.path,
  pageNumber: 1,
  pageBuilder: (context, textureBuilder, pageSize) =>
      textureBuilder(),
),
```

**Error:**
```
E/flutter (24612): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Null check operator used on a null value
E/flutter (24612): #0      PdfDocumentLoaderState._setPageSize (package:pdf_render/pdf_render_widgets.dart:203:45)
E/flutter (24612): #1      PdfPageViewState._init (package:pdf_render/pdf_render_widgets.dart:347:26)
E/flutter (24612): <asynchronous suspension>
E/flutter (24612): 
```

**Comment by espresso3389** [comment]
How do you think to use [pdfrx](https://pub.dev/packages/pdfrx) for your purpose?
I don't want to maintain pdf_render any longer because of its architecture.

**Comment by Yousafkhanzadaa** [comment]
Sure @espresso3389, I try that one. Thank you for the suggestion.
