### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by pinpong** [espresso3389/flutter_pdf_render#34]
```flutter: Null check operator used on a null value

flutter:

#0      PdfDocumentMethodChannel.getPage (package:pdf_render/src/pdf_render_method_channel.dart:100:115)

<asynchronous suspension>

#1      _PdfViewerState.load (package:pdf_render/pdf_render_widgets.dart:766:25)

<asynchronous suspension>

flutter: ----------------------------------------------------

**Comment by espresso3389** [comment]
As I told you once, could you please explain more background for the issue?
Otherwise, I will close your issues.

**Comment by espresso3389** [comment]
Anyway, [1.0.7](https://pub.dev/packages/pdf_render/versions/1.0.7) introduces intermediate error handling mechanism on document open.

**Comment by pinpong** [comment]
New version looks good. Thanks
