### ISSUE TITLE
App crash on android when use in bottom tab bar.

### ISSUE THREAD

**Issue by nimisharanipabacancy** [espresso3389/flutter_pdf_render#61]
I am loading pdf in bottom navigation bar 2 screen. When multiple time click on bottom bar and change screen accordingly, app was crash on android. 

I got following logs in console:
```
E/flutter (18819): 
E/GLConsumer(18819): [SurfaceTexture-0-18819-307] attachToContext: abandoned GLConsumer
E/flutter (18819): [ERROR:flutter/fml/platform/android/jni_util.cc(182)] java.lang.RuntimeException: Error during attachToGLContext (see logcat for details)
E/flutter (18819): 	at android.graphics.SurfaceTexture.attachToGLContext(SurfaceTexture.java:289)
E/flutter (18819): 	at io.flutter.embedding.engine.renderer.SurfaceTextureWrapper.attachToGLContext(SurfaceTextureWrapper.java:55)
E/flutter (18819): 
F/flutter (18819): [FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1231)] Check failed: fml::jni::CheckException(env). 
F/libc    (18819): Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 18854 (1.raster), pid 18819 (mple.torahclass)
*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
Build fingerprint: 'xiaomi/tissot/tissot_sprout:9/PKQ1.180917.001/V10.0.24.0.PDHMIXM:user/release-keys'
Revision: '0'
ABI: 'arm64'
pid: 18819, tid: 18854, name: 1.raster  >>> com.example.torahclass <<<
signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
Abort message: '[FATAL:flutter/shell/platform/android/platform_view_android_jni_impl.cc(1231)] Check failed: fml::jni::CheckException(env). 
'
    x0  0000000000000000  x1  00000000000049a6  x2  0000000000000006  x3  0000000000000008
    x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  8000000000000000
    x8  0000000000000083  x9  ae6c6820a1084bcc  x10 0000000000000000  x11 fffffffc7ffffbdf

```

**Comment by espresso3389** [comment]
I'm not sure whether 6c6f0b6 will fix the issue or not, it may fix certain errors caused by lacking of null-check on updateTex.
Please check [1.0.17](https://pub.dev/packages/pdf_render/versions/1.0.17).

**Comment by nimisharanipabacancy** [comment]
After updating version to 1.0.17 still facing same issue.

**Comment by okbye123** [comment]
This will help https://www.youtube.com/watch?v=gAUVz0U7eyA
