### ISSUE TITLE
await page.render() crashed on web

### ISSUE THREAD

**Issue by vishwajit76** [espresso3389/flutter_pdf_render#66]
pdf is successfully opened but when i try to render page, web app is crashed.

`Error: Expected a value of type 'int', but got one of type 'Null'
    at Object.throw_ [as throw] (http://localhost:49752/dart_sdk.js:5063:11)
    at Object.castError (http://localhost:49752/dart_sdk.js:5022:15)
    at Object.cast [as as] (http://localhost:49752/dart_sdk.js:5347:17)
    at Function.as (http://localhost:49752/dart_sdk.js:19820:19)
    at _render (http://localhost:49752/packages/pdf_render/src/pdf_render_method_channel.dart.lib.js:602:97)
    at _render.next (<anonymous>)
    at http://localhost:49752/dart_sdk.js:40537:33
    at _RootZone.runUnary (http://localhost:49752/dart_sdk.js:40407:59)
    at _FutureListener.thenAwait.handleValue (http://localhost:49752/dart_sdk.js:35328:29)
    at handleValueCallback (http://localhost:49752/dart_sdk.js:35896:49)
    at Function._propagateToListeners (http://localhost:49752/dart_sdk.js:35934:17)
    at _Future.new.[_completeWithValue] (http://localhost:49752/dart_sdk.js:35782:23)
    at async._AsyncCallbackEntry.new.callback (http://localhost:49752/dart_sdk.js:35803:35)
    at Object._microtaskLoop (http://localhost:49752/dart_sdk.js:40675:13)
    at _startMicrotaskLoop (http://localhost:49752/dart_sdk.js:40681:13)
    at http://localhost:49752/dart_sdk.js:36156:9`

**Comment by vishwajit76** [comment]
crashed on pageNumber
` 

        return PdfPageImageMethodChannel._(
        pageNumber: obj['pageNumber'] as int,
        x: obj['x'] as int,
        y: obj['y'] as int,
        width: retWidth,
        height: retHeight,
        fullWidth: obj['fullWidth'] as double,
        fullHeight: obj['fullHeight'] as double,
        pageWidth: obj['pageWidth'] as double,
        pageHeight: obj['pageHeight'] as double,
        pixels: pixels,
        buffer: ptr);
`

**Comment by espresso3389** [comment]
Basically, such error causes on PDF open failure.
On which platform did you get the error?
And, if possible, could you give me the PDF file?

**Comment by vishwajit76** [comment]
Error is occured in Web platform.
[certificate (8).pdf](https://github.com/espresso3389/flutter_pdf_render/files/7768557/certificate.8.pdf)

**Comment by espresso3389** [comment]
I realized that pdf.js thorws an exception during processing the PDF file.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/1311400/147758183-bf270462-4fc2-4080-bcb5-f7267a04993a.png">

```
"Error
    at BaseExceptionClosure (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:1891:29)
    at Object.<anonymous> (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:1894:2)
    at __w_pdfjs_require__ (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:25700:42)
    at Object.<anonymous> (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:60:13)
    at __w_pdfjs_require__ (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:25700:42)
    at https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:25941:22
    at https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:25985:3
    at https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:25988:12
    at webpackUniversalModuleDefinition (https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:31:50)
    at https://file+.vscode-resource.vscode-webview.net/c%3A/Users/kawasaki/.vscode-insiders/extensions/tomoki1207.pdf-1.2.0/lib/build/pdf.js:32:3"
```

I'm not sure whether it is an issue with pdf.js or with the file...

**Comment by espresso3389** [comment]
I could not reproduce the issue on 1.0.18.
Anyway, `getPage` may throw exception on PDF decoder error. And your code should handle exception correctly.

**Comment by espresso3389** [comment]
@vishwajit76 Recent updates contains several null-safety changes. Could you please check the latest version?

**Comment by syonip** [comment]
I'm also getting this.
From what I see there are two problems:
1. If calling page.render() with no params, I get  `PlatformException(error, Exception: Invalid PDF page rendering rectangle (null x null), null, null)` although the docs say `If [width], [height], [fullWidth], [fullHeight], and [dpi] are all 0, the page is rendered at 72 dpi.`
2. If I do send some values to width, height, fullWidth, fullHeight, I get `Expected a value of type 'int', but got one of type 'Null'`
It seems the reason is indeed this code: https://github.com/espresso3389/flutter_pdf_render/blob/85def54ac2278d6398dd915103e4f01f31f88e8e/lib/src/pdf_render_method_channel.dart#L263
All the values in `obj` are null.
I changed the code to this and it works, but I'm not sure about some of the values:
```
return PdfPageImageMethodChannel._(
        pageNumber: pageNumber as int,
        x: x as int,
        y: y as int,
        width: retWidth as int,
        height: retHeight as int,
        fullWidth: fullWidth as double,
        fullHeight: fullHeight as double,
        pageWidth: fullWidth as double,
        pageHeight: fullHeight as double,
        pixels: pixels,
        buffer: ptr);
```

**Comment by espresso3389** [comment]
Could you try [1.3.1](https://pub.dev/packages/pdf_render/versions/1.3.1)?

**Comment by syonip** [comment]
Thanks for quick response. I tested 1.3.1
1. Still getting `Exception: Invalid PDF page rendering rectangle (null x null)` when calling render() with no args.
2. Still getting `Expected a value of type 'int', but got one of type 'Null'` , but now I see the only null value is pageNumber.

**Comment by espresso3389** [comment]
[1.3.4](https://pub.dev/packages/pdf_render/versions/1.3.4) that fixes the issue is just released.
